version: '3.8'
services:
  chat-service:
    build:
      context: ./Messenger
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  web-sockets:
    build:
      context: ./WebSockets
      dockerfile: Dockerfile
    ports:
      - "5002:80"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
